# see: https://github.com/flycheck/emacs-travis
language: emacs-lisp
sudo: required
dist: trusty
cache:
  - directories:
      # Cache stable Emacs binaries (saves 1min per job)
      - "$HOME/emacs/"
# Allow Emacs snapshot builds to fail and donâ€™t wait for these as they can take
# a looooong time
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot
env:
  global:
    - INIT_PACKAGE_EL="(progn (require 'package) (push '(\"melpa\" . \"https://melpa.org/packages/\") package-archives) (push '(\"gnu\" . \"https://elpa.gnu.org/packages/\") package-archives) (package-initialize) (package-refresh-contents))"
    - EMACSCONFFLAGS="--with-x-toolkit=no --without-x --without-all --with-xml2 --with-threads CFLAGS='-O2 -march=native' CXXFLAGS='-O2 -march=native'"
  matrix:
    - EMACS_VERSION=26.0.91 PRETEST=yes
    - EMACS_VERSION=snapshot
before_install:
  - sudo apt-get update
  - sudo apt-get remove gnutls-bin
  - sudo apt-get install ca-certificates build-essential nettle-dev libgmp-dev
  - wget 'https://www.gnupg.org/ftp/gcrypt/gnutls/v3.1/gnutls-3.1.23.tar.xz'
  - unxz gnutls-3.1.23.tar.xz && tar xf gnutls-3.1.23.tar
  - pushd gnutls-3.1.23
  - sudo ./configure && sudo make && sudo make install
  - sudo ln -s /usr/local/lib/libgnutls.so.28 /usr/lib/libgnutls.so.28
  - popd
  # Configure $PATH: Executables are installed to $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  # Download the makefile to emacs-travis.mk
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  # Install Emacs (according to $EMACS_VERSION) and Cask
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
install:
  # Install your dependencies
  - cask install
script:
  # Run your tests
  - cask exec ert-runner
  - cask emacs -Q -batch --eval "${INIT_PACKAGE_EL}" -l package-lint.el -f package-lint-batch-and-exit mpmc-queue.el
  - cask emacs -Q -batch -l mpmc-queue.el --eval "(progn (byte-compile-file \"mpmc-queue.el\") (require 'mpmc-queue) (require 'checkdoc) (with-current-buffer (find-file \"mpmc-queue.el\") (checkdoc-current-buffer t)))"
